# Generated by Django 5.2.1 on 2025-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MorseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morse_code', models.CharField(max_length=10, unique=True)),
                ('character', models.CharField(max_length=1, unique=True)),
            ],
            options={
                'verbose_name': 'Morse Mapping',
                'verbose_name_plural': 'Morse Mappings',
                'ordering': ['character'],
            },
        ),
    ]
